version: '3'
services:
  app-db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pubsub
      POSTGRES_USER: pubsub
      POSTGRES_PASSWORD: pubsub
  pubsub-service:
    depends_on:
      - app-db
    build:
      context: ../
    ports:
      - 8080:8080
    environment:
      DATASOURCE_URL: jdbc:postgresql://app-db:5432/pubsub
      DB_USER: pubsub
      DB_PASSWORD: pubsub

volumes:
  db_data:
    driver: local